---
title: "T4: 13.03.2026"
---

::: {.callout-note title="Lernziele"}

- Effizienten R-Code für automatisiertes Einlesen und Aufbereiten von Daten schreiben können

- Eigene Funktionen in R erstellen können 
:::

**Vorbereitungsauftrag**

- Basics in R: 

    - Die Hauptfunktionen des ``{tidyverse}` (`select()`, `filter()`, `group_by()`, `mutate()`) sicher verstehen und anwenden können
        - [Einführung in R](../chapters/intro_r.html)
        - [Daten importieren und vorverarbeiten mit R](../chapters/basics_datawrangling.html)
    - Ein neues `.Rmd` Dokument erstellen (falls nötig package `{rmarkdown}` installieren)
    - Die Experimentdaten von Ilias herunterladen und in einem `data`-Ordner speichern (im selben Ordner wie das `.Rmd` Dokument)
    - Die Daten im `.Rmd`-Dokument einlesen (mit `read_csv()`) und mit `glimpse()` anschauen 


**Kurstermin**

- [Automatisiertes Preprocessing der Experimentdaten](../chapters/functions_wrangling.html)

- Struktur und Aufbau eigener Funktionen in R 


**Vertiefung für Interessierte (freiwillig)**

- R for Data Sciene (2e) (Buch online): <https://r4ds.hadley.nz/>
